package com.sintra.loanapp.model;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Pattern;

import com.fasterxml.jackson.annotation.JsonIgnoreProperties;
import com.fasterxml.jackson.annotation.JsonManagedReference;

import io.swagger.annotations.ApiModelProperty;

@Entity
@Table(name = "customer")
@JsonIgnoreProperties({ "hibernateLazyInitializer", "handler" })
public class Customer {

	@ApiModelProperty(notes = "The autogenerated customer ID")
	private Long customer_id;
	@ApiModelProperty(notes = "The customer name")
	@NotNull
	@Pattern(regexp = "^[a-zA-Z]*$")
	private String name;
	@NotNull
	@Pattern(regexp = "^[a-zA-Z]*$")
	@ApiModelProperty(notes = "The customer last name")
	private String surname;
	@NotNull
	@Pattern(regexp = "^([a-zA-Z0-9]{3})-([a-zA-Z0-9]{3})-([a-zA-Z0-9]{2})-([a-zA-Z0-9]{2})")
	@ApiModelProperty(notes = "The customer fiscal code")
	private String fiscalCode;
	@ApiModelProperty(notes = "The customer DOB")
	private String dob;
	@NotNull
	@ApiModelProperty(notes = "The customer address")
	private String address;
	@NotNull
	@Pattern(regexp = "^\\d{1,15}$")
	@ApiModelProperty(notes = "The customer cell number")
	private String phone;
	@ApiModelProperty(notes = "The customer loan")
	private Set<Loan> loan = new HashSet<>();

	public Customer() {

	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE)
	public Long getCustomer_id() {
		return customer_id;
	}

	public void setCustomer_id(Long customer_id) {
		this.customer_id = customer_id;
	}

	public String getName() {
		return name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public String getSurname() {
		return surname;
	}

	public void setSurname(String surname) {
		this.surname = surname;
	}

	public String getFiscalCode() {
		return fiscalCode;
	}

	public void setFiscalCode(String fiscalCode) {
		this.fiscalCode = fiscalCode;
	}

	public String getDob() {
		return dob;
	}

	public void setDob(String dob) {
		this.dob = dob;
	}

	public String getAddress() {
		return address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	public String getPhone() {
		return phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "customer")
	@JsonManagedReference
	public Set<Loan> getLoan() {
		return loan;
	}

	public void setLoan(Set<Loan> loan) {
		this.loan = loan;
	}

}
